export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_THEME = 'TOGGLE_THEME';

export const CREATE_BOARD_BEGIN = 'CREATE_BOARDS_BEGIN';
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARDS_SUCCESS';
export const CREATE_BOARD_ERROR = 'CREATE_BOARDS_ERROR';

export const GET_BOARDS_BEGIN = 'GET_BOARDS_BEGIN';
export const GET_BOARDS_SUCCESS = 'GET_BOARDS_SUCCESS';
export const GET_BOARDS_ERROR = 'GET_BOARDS_ERROR';
